# Generated by Django 2.2.5 on 2020-01-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID1', models.IntegerField()),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
