# Generated by Django 2.2.5 on 2020-01-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200121_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdsource',
            name='Gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
    ]
