# Generated by Django 2.2.5 on 2020-01-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20200121_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crowdsource',
            old_name='Stored',
            new_name='Created_By',
        ),
    ]
