# Generated by Django 2.2.5 on 2020-01-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200121_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='location',
            field=models.IntegerField(max_length=6),
        ),
    ]
