# Generated by Django 2.2.5 on 2020-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200121_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
