# Generated by Django 2.2.5 on 2020-01-21 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200121_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedusermodel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='extendedusermodel',
            name='user_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extendeduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
